// İstanbul Women Solidarity and Consultation Centers fallbacks
export interface Center {
  name: string;
  description: string;
  city: string;
  address: string;
  phone: string;
  hours: string;
  photoUrl: string;
  lat: number;
  lng: number;
  category: string;
  district: string;
}

export const FALLBACK_CENTERS: Center[] = [
  {
    "name": "Mor Çatı",
    "description": "Kadın Sığınağı Vakfı",
    "city": "İSTANBUL",
    "address": "Mor Çatı Women's Shelter Foundation",
    "phone": "2126569696",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 41.04028,
    "lng": 28.98603,
    "category": "Kadın Destek Kurumu",
    "district": "İstanbul"
  },
  {
    "name": "Kadav",
    "description": "Kadınlarla Dayanışma Vakfı",
    "city": "İSTANBUL",
    "address": "KADAV – Kadınlarla Dayanışma Vakfı",
    "phone": "2122515850",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 41.00726,
    "lng": 28.79558,
    "category": "Kadın Dayanışma Merkezi",
    "district": "İstanbul"
  },
  {
    "name": "Kedev",
    "description": "Kadın Emeği Değerlendirme Vakfı",
    "city": "İSTANBUL",
    "address": "Kadın Emeğini Değerlendirme Vakfı",
    "phone": "2122922672",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 41.03641,
    "lng": 28.98213,
    "category": "Kadın Destek Kurumu",
    "district": "İstanbul"
  },
  {
    "name": "Kagider",
    "description": "İstanbul Kadın Girişimciğini Destekleyen İş Dünyası Derneği",
    "city": "İSTANBUL",
    "address": "Women Entrepreneurs Association of Turkey",
    "phone": "2122668261",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 41.08079,
    "lng": 28.01056,
    "category": "Kadın Destek Kurumu",
    "district": "İstanbul"
  },
  {
    "name": "İstanbul Barosu Kadın Hakları Merkezi",
    "description": "Hakın Hakları Alanındaki Hukuki Destek Sağlar.",
    "city": "İSTANBUL",
    "address": "Istanbul Bar Association",
    "phone": "2122516325",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFt3rnHI4Y1bKJfYuMqYmEcNO2tfvJJ3ZsiRJcBRoqpJAQQu74htlTAoodpKJeBp8EkcGRgE866iYHOOCmJkieeHPgHpTQxcvJA2BjlKX5U_Sh5EhtC0VDbvkpiiqbN4sqeWB-Ql6Y4e8qn=s1360-w1360-h1020-rw",
    "lat": 41.03075,
    "lng": 28.97503,
    "category": "Kadın Destek Kurumu",
    "district": "İstanbul"
  },
  {
    "name": "Şönim",
    "description": "Şiddet Mağduru Kadılara Koruma Ve Destek Hizmeti",
    "city": "İSTANBUL",
    "address": "İstanbul Valiliği Şiddeti Önleme ve İzleme Merkezi",
    "phone": "2124652196",
    "hours": "7/24",
    "photoUrl": "",
    "lat": 40.96265,
    "lng": 28.8228,
    "category": "ŞÖNİM (Şiddet Önleme ve İzleme Merkezi)",
    "district": "İstanbul"
  },
  {
    "name": "İbb Kadın Ve Aile Hizmetleri Müdürlüğü",
    "description": "Kadınlara Yönelik Sosyal Destek Politikaları Yürütür.",
    "city": "İSTANBUL",
    "address": "İBB Kadın ve Aile Hizmetleri Müdürlüğü",
    "phone": "4448086",
    "hours": "7/24",
    "photoUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwcumNhssmLO9yeeiu3Bgks3fY2bFYUmcLB0ZbkleJV_QblJLTC_Tb8bYVMmDtXT5VK2TqT5XoMLhgs64_Os17DPhfarbqxakkNao4big&s=10",
    "lat": 40.99101,
    "lng": 28.83054,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Çukurova Şiddet Önleme Ve İzleme Merkezi Şönim",
    "description": "Şiddet Mağduru Kadılara Koruma Ve Destek Hizmeti",
    "city": "İSTANBUL",
    "address": "Şiddet Önleme ve İzleme Merkezi",
    "phone": "",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 37.03843,
    "lng": 35.28435,
    "category": "ŞÖNİM (Şiddet Önleme ve İzleme Merkezi)",
    "district": "İstanbul"
  },
  {
    "name": "Adıyaman Şiddet Önleme Ve İzleme Merkezi Şönim",
    "description": "Şiddet Mağduru Kadılara Koruma Ve Destek Hizmeti",
    "city": "İSTANBUL",
    "address": "ŞİDDET ÖNLEME VE İZLEME NERKEZİ MÜDÜRLÜĞÜ ADIYAMAN",
    "phone": "",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 37.76207,
    "lng": 38.29044,
    "category": "ŞÖNİM (Şiddet Önleme ve İzleme Merkezi)",
    "district": "İstanbul"
  },
  {
    "name": "Şişli Belediyesi Kadın Danışma Merkezi",
    "description": "Kadınlara Yönelik Sosyal Destek Merkezi",
    "city": "İSTANBUL",
    "address": "T.C. Şişli Belediyesi Kadın Danışma Merkezi",
    "phone": "4443112",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 41.06477,
    "lng": 28.97096,
    "category": "Kadın Danışma Merkezi",
    "district": "Şişli"
  },
  {
    "name": "Beşiktaş Belediyesi Kadın Danışma Merkezi",
    "description": "Kadın Hakları Ve Destek Hizmetleri",
    "city": "İSTANBUL",
    "address": "Kadın Dayanışma ve Yaşam Merkezi",
    "phone": "4444455",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 41.0766,
    "lng": 29.01567,
    "category": "Kadın Danışma Merkezi",
    "district": "Beşiktaş"
  },
  {
    "name": "Üsküdar Belediyesi Kadın Danışma Merkezi",
    "description": "Kadınlara Psikolojik Ve Sosyal Destek",
    "city": "İSTANBUL",
    "address": "ÜKAD ÜSKÜDAR KADIN VE AİLE DAYANIŞMA MERKEZİ",
    "phone": "2163335225",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 41.0297,
    "lng": 29.02821,
    "category": "Kadın Danışma Merkezi",
    "district": "Üsküdar"
  },
  {
    "name": "Maltepe Belediyesi Kadın Danışma Merkezi",
    "description": "Kadın Dayanışma Ve Destek Merkezi",
    "city": "İSTANBUL",
    "address": "Maltepe Belediyesi Prof.Dr. İoanna Kuçuradi Kadın Danışma Merkezi",
    "phone": "",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 40.9469,
    "lng": 29.10866,
    "category": "Kadın Dayanışma Merkezi",
    "district": "Maltepe"
  },
  {
    "name": "Bakırköy Belediyesi Kadın Danışma Merkezi",
    "description": "Kadınlara Yönelik Sosyal Hizmet Merkezi",
    "city": "İSTANBUL",
    "address": "Istanbul Metropolitan Municipality Woman Coordination Center",
    "phone": "2124149777",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 40.99004,
    "lng": 28.83019,
    "category": "Kadın Danışma Merkezi",
    "district": "Bakırköy"
  },
  {
    "name": "Beylikdüzü Belediyesi Kadın Danışma Merkezi",
    "description": "Kadın Destek Ve Danışmanlık Merkezi",
    "city": "İSTANBUL",
    "address": "Beylikdüzü Belediyesi Kadın ve Aile Hizmetleri Müdürlüğü Danışma Takip ve Rehabilite Hizmetleri",
    "phone": "4440939",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 40.98545,
    "lng": 28.60598,
    "category": "Kadın Danışma Merkezi",
    "district": "Beylikdüzü"
  },
  {
    "name": "Ataşehir Belediyesi Kadın Danışma Merkezi",
    "description": "Kadınlara Sosyal Ve Hukuki Destek",
    "city": "İSTANBUL",
    "address": "Ataşehir Municipality",
    "phone": "",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 40.99722,
    "lng": 29.10075,
    "category": "Kadın Danışma Merkezi",
    "district": "Ataşehir"
  },
  {
    "name": "Kartal Belediyesi Kadın Danışma Merkezi",
    "description": "Kadın Dayanışma Ve Destek Hizmetleri",
    "city": "İSTANBUL",
    "address": "T. C. Kartal Belediyesi KaDin Danişma Merkezi",
    "phone": "2162806406",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 40.89748,
    "lng": 2.918,
    "category": "Kadın Dayanışma Merkezi",
    "district": "Kartal"
  },
  {
    "name": "Zonguldak Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "İSTANBUL",
    "address": "Provincial Directorate of Family and Social Policies, Trabzon",
    "phone": "",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFnrQvPIcVnGjcJgCK4uJTKdl7RnWuUcvkyiY-uHq8OrWWSWAS_Locbhxb28TRbwnbPs9fDZdNOMVZMm4Zi3921r8mworXX2a7KYZBnAKrBAhzV9HrPLToSg5cnccGnKNXFravsJw=s1360-w1360-h1020-rw",
    "lat": 40.99678,
    "lng": 39.74273,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Sultangazi Belediyesi Kadın Danışma Merkezi",
    "description": "Kadın Hakları Ve Sosyal Destek",
    "city": "İSTANBUL",
    "address": "İstanbul Aile Danışmanlık Ve Eğitim Merkezi",
    "phone": "2124593434",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 41.10871,
    "lng": 28.86576,
    "category": "Kadın Danışma Merkezi",
    "district": "Sultangazi"
  },
  {
    "name": "Esenler Belediyesi Kadın Danışma Merkezi",
    "description": "Kadınlara Psikolojik Ve Sosyal Destek",
    "city": "İSTANBUL",
    "address": "ESAYDAM (Esenler Aile Yaşam ve Danışma Merkezi)",
    "phone": "2126295301",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 41.0582,
    "lng": 28.86379,
    "category": "Kadın Danışma Merkezi",
    "district": "Esenler"
  },
  {
    "name": "Gaziosmanpaşa Belediyesi Kadın Danışma Merkezi",
    "description": "Kadın Destek Hizmetleri",
    "city": "İSTANBUL",
    "address": "Gaziosmanpaşa Belediyesi Aile Danişma Merkezi",
    "phone": "4440467",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 41.06032,
    "lng": 28.9084,
    "category": "Kadın Danışma Merkezi",
    "district": "Gaziosmanpaşa"
  },
  {
    "name": "Küçükçekmece Belediyesi Kadın Danışma Merkezi",
    "description": "Kadınlara Yönelik Danışmanlık",
    "city": "İSTANBUL",
    "address": "Kadin Eşitlik Merkezi",
    "phone": "4444360",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 41.02656,
    "lng": 28.79292,
    "category": "Kadın Danışma Merkezi",
    "district": "Küçükçekmece"
  },
  {
    "name": "Yalova Şiddet Önleme Ve İzleme Merkezi Şönim",
    "description": "Şiddet Mağduru Kadılara Koruma Ve Destek Hizmeti",
    "city": "İSTANBUL",
    "address": "Şiddet Önleme ve İzleme Merkezi (ŞÖNİM)",
    "phone": "",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 40.65227,
    "lng": 29.24537,
    "category": "ŞÖNİM (Şiddet Önleme ve İzleme Merkezi)",
    "district": "İstanbul"
  },
  {
    "name": "Avcılar Belediyesi Kadın Ve Aile Sağlığı Merkezi",
    "description": "Kadın Hakları Ve Destek Hizmetleri",
    "city": "İSTANBUL",
    "address": "Avcılar Kadın Ve Aile Sağlığı Mer.",
    "phone": "4446989",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 40.97894,
    "lng": 28.72693,
    "category": "Belediye Destek Birimi",
    "district": "Avcılar"
  },
  {
    "name": "Zeytinburnu Belediyesi Kadın Danışma Merkezi",
    "description": "Kadınlara Sosyal Destek",
    "city": "İSTANBUL",
    "address": "Aile Kadın Destekleme ve Engelliler Merkezi AKDEM",
    "phone": "2124131111",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 40.99498,
    "lng": 28.9086,
    "category": "Kadın Danışma Merkezi",
    "district": "Zeytinburnu"
  },
  {
    "name": "Fatih Belediyesi Kadın Danışma Merkezi",
    "description": "Kadın Dayanışma Merkezi",
    "city": "İSTANBUL",
    "address": "Fatih Belediye Başkanlığı Ana Bina",
    "phone": "2125215363",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 41.0177,
    "lng": 28.94038,
    "category": "Kadın Dayanışma Merkezi",
    "district": "Fatih"
  },
  {
    "name": "Beyoğlu Belediyesi Kadın Danışma Merkezi",
    "description": "Kadınlara Yönelik Sosyal Hizmetler",
    "city": "İSTANBUL",
    "address": "Kadın Sağlığı Danışma Merkezi",
    "phone": "2122440888",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 41.03657,
    "lng": 28.97527,
    "category": "Kadın Danışma Merkezi",
    "district": "Beyoğlu"
  },
  {
    "name": "Ümraniye Belediyesi Kadın Danışma Merkezi",
    "description": "Kadın Destek Ve Danışma Merkezi",
    "city": "İSTANBUL",
    "address": "T.C. Ümraniye Belediyesi",
    "phone": "4449822",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 41.02978,
    "lng": 29.09918,
    "category": "Kadın Danışma Merkezi",
    "district": "Ümraniye"
  },
  {
    "name": "Eyüpsultan Belediyesi Kadın Danışma Merkezi",
    "description": "Kadınlara Sosyal Destek Hizmeti",
    "city": "İSTANBUL",
    "address": "ESADEM - Eyüpsultan Aile Danışmanlık ve Eğitim Merkezi",
    "phone": "2124401544",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 41.04724,
    "lng": 28.9364,
    "category": "Kadın Danışma Merkezi",
    "district": "Eyüpsultan"
  },
  {
    "name": "İstanbul Üniversitesi Kadın Çalışmaları Merkezi",
    "description": "Kadın Çalışmaları Ve Akademik Araştırmalar",
    "city": "İSTANBUL",
    "address": "Istanbul University",
    "phone": "2124400000",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 41.01275,
    "lng": 28.96187,
    "category": "Kadın Destek Kurumu",
    "district": "İstanbul"
  },
  {
    "name": "Boğaziçi Üniversitesi Toplumsal Cinsiyet Merkezi",
    "description": "Kadın Ve Toplumsal Cinsiyet Araştırmaları",
    "city": "İSTANBUL",
    "address": "Boğaziçi University",
    "phone": "2123595400",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 41.08373,
    "lng": 29.05169,
    "category": "Kadın Destek Kurumu",
    "district": "İstanbul"
  },
  {
    "name": "Koç Üniversitesi Toplumsal Cinsiyet Merkezi",
    "description": "Kadın Çalışmaları Akademik Merkezi,",
    "city": "İSTANBUL",
    "address": "Koç Üniversitesi Rumeli Feneri Kampüsü",
    "phone": "2123381000",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 41.19867,
    "lng": 29.07199,
    "category": "Kadın Destek Kurumu",
    "district": "İstanbul"
  },
  {
    "name": "Sabancı Üniversitesi Toplumsal Cinsiyet Forumu",
    "description": "Kadın Eşitliği Üzerine Araştırmalar",
    "city": "İSTANBUL",
    "address": "Sabancı Üniversitesi Bilgi Merkezi",
    "phone": "2164839000",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 40.89029,
    "lng": 29.37722,
    "category": "Kadın Destek Kurumu",
    "district": "İstanbul"
  },
  {
    "name": "Marmara Üniversitesi Kadın Ve Aile Çalışmaları Merkezi",
    "description": "Kadın Çalışmaları Ve Araştırma Merkezi",
    "city": "İSTANBUL",
    "address": "Faculty of Humanities and Sciences",
    "phone": "2167771645",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 40.98728,
    "lng": 29.05401,
    "category": "Kadın Destek Kurumu",
    "district": "İstanbul"
  },
  {
    "name": "Yıldız Teknik Üniversitesi Kadın Çalışmaları Merkezi",
    "description": "Kadın Araştırmaları Ve Akademik Destek",
    "city": "İSTANBUL",
    "address": "Yıldız Technical University",
    "phone": "2123836000",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 41.0522,
    "lng": 29.01054,
    "category": "Kadın Destek Kurumu",
    "district": "İstanbul"
  },
  {
    "name": "Türk Kadınlar Birliği Kadıköy Şubesi",
    "description": "Kadın Hakları Alanında Çalışan Sivil Toplum Örgütü",
    "city": "İSTANBUL",
    "address": "Türk Kadınlar Birliği Kadıköy Şubesi",
    "phone": "2164148616",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 40.99006,
    "lng": 29.02772,
    "category": "Kadın Destek Kurumu",
    "district": "Kadıköy"
  },
  {
    "name": "Ka-der İstanbul Şubesi",
    "description": "Şiddet Mağduru Kadılara Koruma Ve Destek Hizmeti",
    "city": "İSTANBUL",
    "address": "Ka-Der",
    "phone": "2122732536",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 40.99562,
    "lng": 29.03888,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Uşak Şiddet Önleme Ve İzleme Merkezi Şönim",
    "description": "Şiddet Mağduru Kadılara Koruma Ve Destek Hizmeti",
    "city": "UŞAK",
    "address": "Uşak ŞÖNİM",
    "phone": "2124494422",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 38.66737,
    "lng": 29.42079,
    "category": "ŞÖNİM (Şiddet Önleme ve İzleme Merkezi)",
    "district": "İstanbul"
  },
  {
    "name": "Antalya Şiddet Önleme Ve İzleme Merkezi Şönim",
    "description": "Şiddet Mağduru Kadılara Koruma Ve Destek Hizmeti",
    "city": "ANTALYA",
    "address": "ŞÖNİM",
    "phone": "0242 227 20 62",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 36.8911,
    "lng": 30.69601,
    "category": "ŞÖNİM (Şiddet Önleme ve İzleme Merkezi)",
    "district": "İstanbul"
  },
  {
    "name": "Ardahan Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Sosyal Destek Hizmeti",
    "city": "ARDAHAN",
    "address": "Ardahan Aile ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0478 211 57 77",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 41.11085,
    "lng": 42.69969,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Aydın Valiliği Şiddet Önleme Ve İzleme Merkezi Müdürlüğü",
    "description": "Şiddet Mağduru Kadılara Koruma Ve Destek Hizmeti",
    "city": "AYDIN",
    "address": "Aydın Valiliği Şiddet Önleme ve İzleme Merkezi Müdürlüğü",
    "phone": "256 214 55 10",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 37.85372,
    "lng": 27.84667,
    "category": "ŞÖNİM (Şiddet Önleme ve İzleme Merkezi)",
    "district": "İstanbul"
  },
  {
    "name": "Balıkesir Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Sosyal Destek Hizmeti",
    "city": "BALIKESİR",
    "address": "Balıkesir Aile ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0266 249 29 73",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 39.64814,
    "lng": 27.84878,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Bayburt Aile, Çalışma Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "BAYBURT",
    "address": "Bayburt Aile, Çalışma ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0458 211 46 01",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 40.25397,
    "lng": 40.22385,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Aile Ve Sosyal Hizmetler İl Müdürlüğü Bilecik",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "BİLECİK",
    "address": "Aile ve Sosyal Hizmetler İl Müdürlüğü Bilecik",
    "phone": "0228 212 20 35",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 40.13363,
    "lng": 29.97632,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Bingöl İl Sosyal Hizmetler Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "BİNGÖL",
    "address": "Il Sosyal Hizmetler Mudurlugu",
    "phone": "0426 213 15 40",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 38.88381,
    "lng": 40.49573,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Bolu Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "BOLU",
    "address": "Bolu Aile ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0374 215 81 76",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 40.74599,
    "lng": 31.60575,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Bursa Şiddet Önleme Ve İzleme Merkezi Şönim",
    "description": "Şiddet Mağduru Kadılara Koruma Ve Destek Hizmeti",
    "city": "BURSA",
    "address": "ŞİDDET ÖNLEME VE İZLEME MERKEZİ",
    "phone": "0248 233 18 41",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 40.18908,
    "lng": 29.04724,
    "category": "ŞÖNİM (Şiddet Önleme ve İzleme Merkezi)",
    "district": "İstanbul"
  },
  {
    "name": "Çanakkale Şiddet Önleme Ve İzleme Merkezi Şönim",
    "description": "Şiddet Mağduru Kadılara Koruma Ve Destek Hizmeti",
    "city": "ÇANAKKALE",
    "address": "Şiddet Önleme ve İzleme Merkezi",
    "phone": "0224 223 03 68",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 40.12271,
    "lng": 26.41295,
    "category": "ŞÖNİM (Şiddet Önleme ve İzleme Merkezi)",
    "district": "İstanbul"
  },
  {
    "name": "Çorum Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "ÇORUM",
    "address": "Aile ve Sosyal Hizmetler İl Müdürlüğü, Çorum",
    "phone": "0286 218 09 82",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEBc7-ZlKFzH-cO9TYDNnKOarjfH9ikXVWkmWWcIvtZDpsTO7M9J4RYZreb_3m0a3gspLx_NENbrW7t8SY6m7ZqrXytbGI4oxsijz9jsWBnfDkBF1vAbyCCOwcp0Jm_fowpA-Sx6Q=s1360-w1360-h1020-rw",
    "lat": 40.5524,
    "lng": 34.95948,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Çankırı Aile, Çalışma Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "ÇANKIRI",
    "address": "Çankırı Aile, Çalışma ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0364 224 65 32",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 40.59964,
    "lng": 33.61756,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Denizli Valiliği Şiddet Önleme Ve İzleme Merkezi",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "DENİZLİ",
    "address": "Denizli Valiliği Şiddet Önleme Ve İzleme Merkezi",
    "phone": "0376 213 26 89",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 37.73189,
    "lng": 29.13054,
    "category": "ŞÖNİM (Şiddet Önleme ve İzleme Merkezi)",
    "district": "İstanbul"
  },
  {
    "name": "Düzce Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "DÜZCE",
    "address": "Düzce Aile ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0 258 266 41 66",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHzdM362m5exQYdyzw9RagaraQhf3fz9ysdovRjM0goF8N0gJIAlYLlu0F17E8zASedZTqiOVn8AQze5XaIt7xusWxGciEmT8RrNqN-K8ElORP2bTRffEhN21CGWQ_DgZR493JV=s1360-w1360-h1020-rw",
    "lat": 40.84559,
    "lng": 31.14147,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Edirne Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "EDİRNE",
    "address": "Edirne Aile ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0380 512 33 40",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGkNgeiGau2zLqEUt5UTvJiqSc503wrq9btjh0xRPCpDeL1hMJvQvOPzIy6rRd4jFjQu3ofMM2qRPexbO-6IDp0tQR0s4gLGTDejsDVaiUv9FhpV8xjF5rlS6c4wGwkKsP8lqoh=s1360-w1360-h1020-rw",
    "lat": 41.67276,
    "lng": 26.57955,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Erzincan Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "ERZİNCAN",
    "address": "Erzincan Provincial Directorate of Family and Social Policies",
    "phone": "0284 212 25 89",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHEg7p1yl4zZFSMcmraz9SmCN5aMOqXEFCPy5g1BcfwI9lH7RrMr2bF_fEBIXs5FuPQysY7W6M4S-FXDxCPS-VmqxGrwsMYRxToV0vga1pLrbMcKeHvD9fXZWkYgVaETn-op5pe=s1360-w1360-h1020-rw",
    "lat": 39.746,
    "lng": 39.51144,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Erzurum Şiddet Önleme Ve İzleme Merkezi Müdürlüğü",
    "description": "Şiddet Mağduru Kadılara Koruma Ve Destek Hizmeti",
    "city": "ERZURUM",
    "address": "Erzurum Aile ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0446 214 38 47",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 39.8993,
    "lng": 41.27798,
    "category": "ŞÖNİM (Şiddet Önleme ve İzleme Merkezi)",
    "district": "İstanbul"
  },
  {
    "name": "Eskişehir Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "ESKİŞEHİR",
    "address": "Eskişehir Aile ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0442 215 14 00",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFYErX_BcogmxXOhoGCEEVy1ZRoSKAV5F2dZlk6DdYAvfkUAxpaGK9QAsnUKD5dwwrCIDNWc87x91Zbp1sS1fov0XFcPOfZ5wbgsGSY3ta9AoaPy3NXsQVsABEp2oY7T-K-8-ccfQ=s1360-w1360-h1020-rw",
    "lat": 39.76609,
    "lng": 30.53934,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Gaziantep Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "GAZİANTEP",
    "address": "GAZİANTEP AİLE ve SOSYAL HİZMETLER İL MÜDÜRLÜĞÜ",
    "phone": "0222 217 46 05",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHozHIp8rUcgprrRcsfO7uv1OJMejZmcnI-h4z8rZBZnF9eXwts5iGzrps8I1c8o_WSTKJzxZrCBxDeIrF0WuCeqXhW8ywxQeZ4PDHRiUwyYf-SHzbasn6KBBxyP1hHRPJiprca=s1360-w1360-h1020-rw",
    "lat": 37.08086,
    "lng": 37.35335,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Giresun Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "GİRESUN",
    "address": "Giresun Aile ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0 342 231 65 21",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFf0mRiCUXYW6fysYKjX5RBzCOvazna5BzBkkqf5UHle_Uh5DOR_bCQO47MtiV0_fcjb3318qK7f3fRLGRuqHZskuMDwq9GNh8rXYBtKgsgGfW1qd4bi-qAIPYMxClJ-eU83FeUdw=s1360-w1360-h1020-rw",
    "lat": 40.90819,
    "lng": 38.36145,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Gümüşhane Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "GÜMÜŞHANE",
    "address": "Il Sosyal Hizmetler Mudurlugu",
    "phone": "0454 215 75 35",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 40.4657,
    "lng": 39.46156,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Hakkari Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "HAKKARİ",
    "address": "Hakkari Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0456 213 19 01",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 37.5809,
    "lng": 43.73577,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Hatay Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "HATAY",
    "address": "Hatay Aile ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0438 211 99 19",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 36.21256,
    "lng": 36.1614,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Isparta Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "ISPARTA",
    "address": "Isparta Aile ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0326 216 10 89",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 37.77094,
    "lng": 30.54902,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "İzmir Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "İZMİR",
    "address": "İzmir Aile ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0 246 223 49 40",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 38.42422,
    "lng": 27.14168,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Kahramanmaraş Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "KAHRAMANMARAŞ",
    "address": "Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0 232 446 33 52",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFg1uLZTym2hpXxwkgoNjgnvClf0s9Us7kNPokWLZ6A3-ooRVBAeRh_AE4iaBkyhEEPv0Z_3Z1L6dqNu_oasQCFQjapGczJe7b1poixVUzHoNcgOvA8EdFK9nZaRDfz4vVDwXkQ=s1360-w1360-h1020-rw",
    "lat": 37.59007,
    "lng": 36.87714,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Kahramanmaraş Şiddet Önleme Ve İzleme Merkezi Şönim",
    "description": "Şiddet Mağduru Kadılara Koruma Ve Destek Hizmeti",
    "city": "KAHRAMANMARAŞ",
    "address": "Kahramanmaraş Şiddet Önleme ve İzleme Merkezi (ŞÖNİM)",
    "phone": "0 344 215 86 45",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 37.58995,
    "lng": 36.87886,
    "category": "ŞÖNİM (Şiddet Önleme ve İzleme Merkezi)",
    "district": "İstanbul"
  },
  {
    "name": "Karabük Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "KARABÜK",
    "address": "T.C. Karabak Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0 344 215 16 26",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 41.20091,
    "lng": 32.62641,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Karaman Aile Ve Sosyal Politikalar İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "KARAMAN",
    "address": "Aile ve Sosyal Politikalar Il Mudurlugu",
    "phone": "0 370 412 23 48",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHIJ2GmL0L8dTyG8SMHNRUQPfPrd0Q2WvwxlZB7K7RuE0WLF7D82M8xsw7tNb3Q3t1NkcXG78xSOXON2de-EUqhEkoKGbBcepJcV8-XOP9lLCSycSqCtCUL2XX7fNaISi_hLOrUhA=s1360-w1360-h1020-rw",
    "lat": 37.18467,
    "lng": 33.21774,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Kars Aile, Çalışma Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "KARS",
    "address": "Kars Aile, Çalışma ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0 338 213 75 16",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAG8agy_Q3_M4EK-LUpERldNv2N4Q50O-flT7SpuwH9sdkZZpS6xfZrDy3xeQj3Jfsf0KbDCQZiNEvlwvKKo91SWq5rt2myZZsH8LzfH7484KFJ8DpB4Ycc8YW7l1dDvH5HiCz74Zw=s1360-w1360-h1020-rw",
    "lat": 40.6013,
    "lng": 43.09205,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Kastamonu Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "KASTAMONU",
    "address": "Kastamonu Aile Ve Sosyal Politikalar Il Müdürlüğü",
    "phone": "0474 212 69 10",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHikTkq_h2wl3ci8cXJXmLjenHk5V03hZIOlHBeZGvGc_-9ITHPwJOKtETkJps4iuGj_aYF7xk0R9LxiF5woQ0K3RVpM70CqF0t5Q4cUo7QUq8k2qZH7aFpzlvD9w2qq5Yezv8=s1360-w1360-h1020-rw",
    "lat": 41.36989,
    "lng": 33.77046,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Kastamonu İli Sosyal Yardımlaşma Ve Dayanışma Vakfı",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "KASTAMONU",
    "address": "Kastamonu Ili Sosyal Yardimlasma ve Dayanisma Vakfi",
    "phone": "0366 214 92 18",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHtwtStLQv4rl8js3zBNz9cvFBy1Ffy9vu0BhZkVq5OE__X1zuNcaygqVsujNGPf8zQzUXqktWx_3QUq0WRQFL6ykidCIIjpWTBipVZ18whfgML7pS23Ak_yCRl0nwmm1mCxduW=s1360-w1360-h1020-rw",
    "lat": 41.71765,
    "lng": 33.82667,
    "category": "Kadın Dayanışma Merkezi",
    "district": "İstanbul"
  },
  {
    "name": "Kayseri Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "KAYSERİ",
    "address": "Kayseri Aile ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0 352 221 34 91",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 38.70986,
    "lng": 35.50397,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Kırklareli Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "KIRIKLARELİ",
    "address": "Kırklareli Aile ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0 288 214 44 41",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHZq0qw0-98z6qR7MQNUY6RImlbU1hHNwFwY0sjg7s0DEFtMxP13vw0ya9aj3ocmPnwnj4Zen7X75CfBqyDTaEBMSpH58UBPjph27Qg7beanLbTpofKCNBpFEsEUY3bzYcPs7nbig=s1360-w1360-h1020-rw",
    "lat": 41.73274,
    "lng": 27.23437,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Kırklareli Şiddet Önleme Ve İzleme Merkezi Müdürlüğü",
    "description": "Şiddet Mağduru Kadılara Koruma Ve Destek Hizmeti",
    "city": "KIRIKLARELİ",
    "address": "Kırklareli Şiddet Önleme ve İzleme Merkezi Müdürlüğü",
    "phone": "0 288 212 18 39",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 41.73223,
    "lng": 27.23432,
    "category": "ŞÖNİM (Şiddet Önleme ve İzleme Merkezi)",
    "district": "İstanbul"
  },
  {
    "name": "Kırşehir Aile Ve Sosyal Politikalar İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "KIRŞEHİR",
    "address": "Kırşehir Aile, Çalışma ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0 386 262 11 66",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHEP8Foc5WEZsWrbrrtKtuQQfJzdCW6T62kearsyjPiy860EZPE8iN3R4VMK78PNVCGrPPdU4p7dEKu2OSu19SVtAX-UhxKarT-HnjS0kb5KLswgqeTSBe8T-hhzB6uoLyBLto_=s1360-w1360-h1020-rw",
    "lat": 39.1649,
    "lng": 34.15442,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Kocaeli Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "KOCAELİ",
    "address": "Kocaeli Aile ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0 262 323 20 07",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFLsbp4NLHM5JdlQNXZPffntfmCkShi-48h5LO6cCl05h83xpC1mNNwcqU0IrHHsYzJEqurc4kR-O58zKqZbwdh9M_lFgoyuo4CfUy5cKXf-NxJUY1oX_pRrWcc-IiNhzsUgHr5=s1360-w1360-h1020-rw",
    "lat": 40.76512,
    "lng": 29.95963,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Kütahya Aile Çalışma Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "KÜTAHYA",
    "address": "KÜTAHYA AİLE ÇALIŞMA VE SOSYAL HİZMETLER İL MÜDÜRLÜĞÜ",
    "phone": "0 274 333 24 53",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAG4jXin9W9lznMnDYj169_Q2FiAXXxlQea6wgo7rH5wf-_blAnxwEguCkVyZEkwKsVuLg2vqDVxSQ3wvqnWmQN3OzQH2tFMyT-JmXRSmdVIlkGmIT7oYEDCLfR03q6Yv3w2EgW4=s1360-w1360-h1020-rw",
    "lat": 39.41902,
    "lng": 29.99489,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Malatya Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "MALATYA",
    "address": "Malatya Aile ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0 422 325 99 22",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEt_cGdhz1pmNYinXiRy9wN5TQ21cOMAY7gsp2N5yUmq0FDuu2VOeyGUDGiP4KG8orFTrfPErEPxA2lmXL1fN_zEKmLjAgNRJoRA4jVEV3LBQ9ZMpqQMe0KNbzZq8s7kWI-GGgUHQ=s1360-w1360-h1020-rw",
    "lat": 38.3432,
    "lng": 38.3135,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Mardin Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "MARDİN",
    "address": "Mardin Aile ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0 482 502 03 68",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 37.33425,
    "lng": 40.69136,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Manisa Şiddet Önleme Ve İzleme Merkezi Müdürlüğü",
    "description": "Şiddet Mağduru Kadılara Koruma Ve Destek Hizmeti",
    "city": "MANİSA",
    "address": "Manisa Şiddet Önleme ve İzleme Merkezi Müdürlüğü",
    "phone": "0 236 232 46 84",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 38.61532,
    "lng": 27.41634,
    "category": "ŞÖNİM (Şiddet Önleme ve İzleme Merkezi)",
    "district": "İstanbul"
  },
  {
    "name": "Niğde Aile Ve Sosyal Hizmetler Bakanlığı",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "NİĞDE",
    "address": "Niğde Aile Ve Sosyal Politikalar İl Müdürlüğü",
    "phone": "0 388 232 34 02",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHt-CcMzIxvU31gC_UrGn3mzR8yf7J-XN3NK_D2HYF2HJsEebRXxupAdTS-gwb4WZW0aMG3JB2cwR3mE17JBEpg_FFfOKImjtkhFtNtf59ql982tripIwKnARD0rFnELx3jYeAoUES3BjNB=s1360-w1360-h1020-rw",
    "lat": 37.9661,
    "lng": 34.70209,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Ordu Şiddet Önleme Ve İzleme Merkezi Müdürlüğü Şönim",
    "description": "Şiddet Mağduru Kadılara Koruma Ve Destek Hizmeti",
    "city": "ORDU",
    "address": "Ordu Şiddet Önleme ve İzleme Merkezi Müdürlüğü (ŞÖNİM)",
    "phone": "0 452 233 33 27",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHk0S2xw2VDVrQwPPK-dh5hXR30JaYJ_whYtzQ5gSsLUlU6ztI720-cZtvB9Ijj3yrAazDOsRK6jMqXtu0CR4F11w4azJPbKqKvtPf_VfYbUo-9X6K2G6JL2E0LytxF2xZrtb0=s1360-w1360-h1020-rw",
    "lat": 40.95723,
    "lng": 37.90319,
    "category": "ŞÖNİM (Şiddet Önleme ve İzleme Merkezi)",
    "district": "İstanbul"
  },
  {
    "name": "Osmaniye Aile, Çalışma Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "OSMANİYE",
    "address": "Aile Ve Sosyal Politikalar İl Müdürlüğü",
    "phone": "0 328 825 01 61",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAE5gFmnDrRMgSgw6yVHBczEP3JZpxdyeCWpdroHhMaUqOxShSgsM68_p5gCwo5uHVOZSw6ysjDx1UlTIkQWxTssm3KZ_0etwOUNlfsK7e2b3Ao4-tFQen18do-j85IZM8fu3nwn=s1360-w1360-h1020-rw",
    "lat": 37.05809,
    "lng": 36.21719,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Rize Aile, Çalışma Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "RİZE",
    "address": "Rize Aile, Çalışma ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0 464 213 04 04",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAF12tQmwRp7jMa3Oxi12BrSpNOkHMbmPCdcwVjEt2HvHck7udOPuYlNx8ThpEguNjedIURgOhCs9NFJh8faeyEPgUvd5VsJC3CQ14G3Qk-hBukIjMSqZDWXTxDGgkPhj6u3Ns6Q6Q=s1360-w1360-h1020-rw",
    "lat": 41.02242,
    "lng": 40.52855,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Sakarya Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "SAKARYA",
    "address": "Aile ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0 264 277 36 87",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH2wqDaaSvUbbYKX7lQ5OeqVtdMYkaCw9ZgHcY8Qoumi7PrPTKdmb51nwkpsPyNgLec8WfWJvVLd5Cayp_vMiNaL9sxRNYyI7wNA8Oq16GbB5P9E3jNg_zSFsHy1rEdxdEUxAeI=s1360-w1360-h1020-rw",
    "lat": 40.7602,
    "lng": 30.39115,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Samsun Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "SAMSUN",
    "address": "Samsun Provincial Directorate of Family and Social Policies",
    "phone": "0 362 435 59 45",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHcuhaKl5RsUxSsjMN7g2_c5-fk0m-IKbSQp1ccBjZwQM0FCS-lh3AGQvzLj_SLIlq8pZ0b0IHfF1lX-EjloAFQmwBnLq3T-3DUmT0WZF7ScSWvu9llijbdeEHeDgmNcHc1Lmqc=s1360-w1360-h1020-rw",
    "lat": 41.28662,
    "lng": 36.33583,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Samsun Şiddet Önleme Ve İzleme Merkezi Müdürlüğü",
    "description": "Şiddet Mağduru Kadılara Koruma Ve Destek Hizmeti",
    "city": "SAMSUN",
    "address": "Samsun Şiddet Önleme ve İzleme Merkezi Müdürlüğü",
    "phone": "0 362 431 11 87",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEYAuI9RrWsa6MdLQLV7sggzlmEahZ_PYGX8fn_RHvUa2fVyKOvq1cu4g_zspm-DZbAzTQUs5qwl4zt3xsv8bRBf0YIPVliEoar4aJ9aHt-vaewFBC0VtEaIi6XdkSSdekfiANe=s1360-w1360-h1020-rw",
    "lat": 41.28928,
    "lng": 36.32975,
    "category": "ŞÖNİM (Şiddet Önleme ve İzleme Merkezi)",
    "district": "İstanbul"
  },
  {
    "name": "Siirt İl Sosyal Hizmetler Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "SİİRT",
    "address": "Il Sosyal Hizmetler Mudurlugu",
    "phone": "0 484 223 22 77",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGUuxGXOHBtea2yLjy_AgprHCjmwpN_Xl8BZwKQLC7HEKVoV59Bw7B34efBVU70m9tBD8aN2UDT0AQ91HeVcyoSUF1hw583uqhFKMJKFzvgaYj6F3iOTXA6YxD5w6F4OZTdzuO7mw=s1360-w1360-h1020-rw",
    "lat": 37.9321,
    "lng": 41.94336,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Sinop Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "SİNOP",
    "address": "Sinop Aile ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0 368 261 52 27",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGHLTczEcmMMI7JtHSR0rlDdK-3V1Pe1jqw2ErDMKei58nbSw0JJp0FPD7UDkFwn138GkGkJGU0Yiw8X35WfUTno8DTELhEx8Jr6COpMIMwbycTyeSdNJRx_WIJSf2LRCa2N5Pc=s1360-w1360-h1020-rw",
    "lat": 42.01991,
    "lng": 35.1302,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Sivas Aile Ve Sosyal Politikalar İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "SİVAS",
    "address": "Sivas Aile Ve Sosyal Politikalar İl Müdürlüğü",
    "phone": "0 346 221 15 00",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGRS7WX1vS4G8apRMMQMozK5O0Xqq5vgn2ldy4QtAusBtBQceI5LTUS_6FXtkBKAA5cia1iqCifjYE7DL-XMvQ_WCzmpDDTO9XxrffDwXnzmKl7fVFy3idwBQ7FrDX36yi8Awo=s1360-w1360-h1020-rw",
    "lat": 39.75412,
    "lng": 37.01939,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Şanlıurfa Aile, Çalışma Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "ŞANLIURFA",
    "address": "Şanlıurfa Aile, Çalışma ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0 414 313 11 61",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFMxc6VH0wubwVT7mSIac9lh_UNm0iCU2m-2SZ7aaBvHX_foHpk6_QKwvAcS8hfgqVHmOpavqKuG_uMF46wCVxYT4HRmg5qlMWgE6Zj0_3Aqf89jp0SKBd77laS7AtgKTHWwnYk7OhfANkn=s1360-w1360-h1020-rw",
    "lat": 37.18581,
    "lng": 38.79993,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Şanlıurfa Şiddet Önleme Ve İzleme Merkezi Şönim",
    "description": "Şiddet Mağduru Kadılara Koruma Ve Destek Hizmeti",
    "city": "ŞANLIURFA",
    "address": "Şanlıurfa Şiddet Önleme ve İzleme Merkezi (ŞÖNİM)",
    "phone": "0 414 313 56 31",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAE9-R4NXAndsh9QK1NBPTYL1zFy3Y8EOgMwIKgtm7zL8Sv8wFzYQcroAq7B-D3JdU_Ql4uaN8ziVD7wrDVq3agxJNuL3GPhzX1Tf-1IICU2Fsb3AhXDAzO-oX3HJz-qSMWVD6S5BQe3TmHt=s1360-w1360-h1020-rw",
    "lat": 38.18265,
    "lng": 38.77772,
    "category": "ŞÖNİM (Şiddet Önleme ve İzleme Merkezi)",
    "district": "İstanbul"
  },
  {
    "name": "Tekirdağ Aile Ve Sosyal Hizmetler İl Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "TEKİRDAĞ",
    "address": "Tekirdağ Aile ve Sosyal Hizmetler İl Müdürlüğü",
    "phone": "0 282 261 12 88",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 40.98733,
    "lng": 27.51365,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Şırnak İl Sosyal Hizmetler Müdürlüğü",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "ŞIRNAK",
    "address": "Il Sosyal Hizmetler Mudurlugu",
    "phone": "0 486 216 29 83",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "",
    "lat": 37.51844,
    "lng": 42.45892,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  },
  {
    "name": "Aile, Çalışma Ve Sosyal Hizmetler İl Müdürlüğü, Trabzon",
    "description": "Aile İçi Sosyal Destek Hizmeti",
    "city": "TRABZON",
    "address": "Provincial Directorate of Family and Social Policies, Trabzon",
    "phone": "0 462 230 19 79",
    "hours": "hafta içi 09.00-17:00",
    "photoUrl": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHxBJIEOM0YDK8KIE-Boo46Mg1R8KpWduuooe1X6znj_3QoPg0BQ8wtwJNxvvYtlUOa7QTWxgxPoWybV1oWTFh_BiSUBtAxqZI8TzJdEUYKu71KVf44wVIGT2IjlHgdYYVgy6k=s1360-w1360-h1020-rw",
    "lat": 40.99704,
    "lng": 39.74264,
    "category": "Belediye Destek Birimi",
    "district": "İstanbul"
  }
];
